# Generated by Django 5.0.4 on 2024-05-05 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todolist_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 5, 18, 17, 42, 871222)),
        ),
    ]
