# Generated by Django 5.0.4 on 2024-05-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todolist_completion_time_todolist_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
