# Generated by Django 5.0.4 on 2024-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_rename_user_id_todolist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.SmallIntegerField(blank=True, choices=[('Important and Urgent', 1), ('Important', 2), ('Urgent', 3), ('Not Urgent, Important', 3)]),
        ),
    ]
