# Generated by Django 5.0.4 on 2024-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_todolist_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Important and Urgent'), (2, 'Important'), (3, 'Urgent'), (4, 'Not Urgent, Important')], null=True),
        ),
    ]
