# Generated by Django 5.0.4 on 2024-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_todolist_category_alter_todolist_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
