# Generated by Django 5.0.4 on 2024-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.ImageField(upload_to='static/image/'),
        ),
    ]
