# Generated by Django 5.0.4 on 2024-06-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_alter_usersetting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='order_by',
            field=models.CharField(choices=[('d', 'due_date'), ('t', 'title')], default='due_date', max_length=1),
        ),
    ]
