# Generated by Django 5.0.4 on 2024-06-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0017_alter_usersetting_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='order_by',
            field=models.CharField(choices=[('d', 'due_date'), ('t', 'title'), ('c', 'creation_date')], default='due_date', max_length=1),
        ),
    ]
