# Generated by Django 5.0.4 on 2024-05-05 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('priority', models.SmallIntegerField(blank=True)),
                ('category', models.IntegerField(blank=True)),
                ('creation_date', models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 5, 18, 13, 24, 733171))),
            ],
        ),
    ]
