# Generated by Django 5.0.4 on 2024-05-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_todolist_completion_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='user_id',
            new_name='user',
        ),
    ]
