# Generated by Django 5.0.4 on 2024-05-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_features_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.ImageField(upload_to='media/image/'),
        ),
    ]
